### ISSUE TITLE
Not able to take the screenshot of the non visible portion of the same activity

### ISSUE THREAD

**Issue by dev057** [nisrulz/screenshott#4]
Please fill out the blanks below describing your issue

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …
…

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, bugreport etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Device Information:** …

**Android Version:** …

**Configuration Information:** …

[More related information if you have can provide]

**Comment by nisrulz** [comment]
@dev057 can you provide more information?

**Comment by dev057** [comment]
Lets say there is an activity having a scrollview. On calling the method for screenshots, I want to capture the screenshot having even that portion of the activity which is not currently shown to the user i.e. user can see those parts if he scrolls up/down. But as of now, it is showing only that part of the activity which is visible to the user. Moreover, if there is a dialog appearing over the screen, will that also be captured in the screenshot?

**Comment by nisrulz** [comment]
@dev057 the current version of screenshott doesnot support this functionality, but I can look into it.

There are alternatives available though: https://github.com/PGSSoft/scrollscreenshot

**Comment by nisrulz** [comment]
@dev057 I am closing this issue, as this is beyond the scope of this library.
